apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front
  name: front
  namespace: u-tbmdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      containers:
      - image: younsssdocker/schoolproject:v3
        name: schoolproject
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: {{ .Values.database.name }}
        - name: DB_USER
          value: {{ .Values.database.user }}
        - name: DB_PASSWORD
          value: {{ .Values.database.password }}
        - name: DB_HOST
          value: db-0
        - name: DB_PORT
          value: "3000"
        resources: {}
status: {}
