apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: front
  name: front
  namespace: u-tbmdn
spec:
      containers:
      - image: younsssdocker/schoolproject:v3
        name: schoolproject
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: {{ .Values.database.name }}
        - name: DB_USER
          value: {{ .Values.database.user }}
        - name: DB_PASSWORD
          value: {{ .Values.database.password }}
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_PORT
          value: "3000"
        resources: {}
status: {}
