FROM registry.glouton.int.nbyt.fr/commun/devops/ci/python3.12:latest

WORKDIR /app

COPY django-site/web /app

RUN chmod +x /app/entrypoint.sh

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

CMD ["/bin/sh", "/app/entrypoint.sh"]
