FROM python:latest

WORKDIR /app

COPY django-site/web /app

RUN chmod +x /app/entrypoint.sh

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000"]
