# Generated by Django 5.1 on 2024-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.FloatField(choices=[(1.0, 'Upvote'), (-1.0, 'Downvote')]),
        ),
    ]
