apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.database.host }}
  name: {{ .Values.database.host }}
spec:
  ports:
  - port: 5432
  selector:
    app: db
  clusterIP: None 
status:
  loadBalancer: {}
