# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.database.host }}
#   labels:
#     app: {{ .Values.database.host }}
# spec:
#   ports:
#   - name: 3000-5432
#     port: 3000
#     protocol: TCP
#     targetPort: 5432
#   clusterIP: None
#   selector:
#     app: db

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.database.host }}
  name: {{ .Values.database.host }}
spec:
  ports:
  - name: 3000-5432
    port: 3000
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
  type: ClusterIP
status:
  loadBalancer: {}
