apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-service
  name: front-service
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: front
status:
  loadBalancer: {}
